server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
#  servlet:
#   context-path: /longe
spring:
  profiles:
    active: @spring.active@
  mvc:
    favicon:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  security:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      pool-prepared-statements: true
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /admin/druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: longe
    jedis:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 20
        max-wait: 1000ms
  mail:
    host: smtp.qq.com
    username: 764252907@qq.com
    password: dnnzingoypzebfhg
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true  
          required: true
        debug: true
    default-encoding: UTF-8
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .html
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
    settings:
      default_encoding: UTF-8
      classic_compatible: true
      whitespace_stripping: true
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      tag_syntax: auto_detect
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.##
      boolean_format: true,false
      auto_import: /le.html as le
    allow-request-override: false

mybatis-plus:
  mapper-locations: classpath*:com/le/**/*/mapper/xml/*.xml
#  type-aliases-package: com.le.**.entity
  type-enums-package: com.le.**.enums
  global-config:
    db-config:
      id-type: ID_WORKER
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  config: classpath:config/logback-longe.xml
  path: longe-logs
longe:
  wechat:
    cert-path: c:/cert/pub/apiclient_cert.p12

---

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.180:3306/lecore_v2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 666666
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lecore_v2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: longe

---

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lecore_v2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 666666
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: longe